#!/usr/bin/env bash
# Nginx setup script
sudo su
apt-get -y install nginx
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
printf "http {\nserver {\nlisten 80;\nroot /var/www/data/;\n}\n}\nevents{}" >> /etc/nginx/nginx.conf
mkdir /var/www/data
printf "Hello World!" >> /var/www/data/index.html
nginx -s reload
