#!/usr/bin/env bash
# Checks the condition of the school file.
file=school
if [[ -e $file ]]
then
	echo "school file exist"
	if [[ -f $file ]]
	then
		echo "school is a regular file"
	fi
	if [[ -s $file ]]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
