#!/usr/bin/env bash
# Nginx setup script
sudo apt-get -y install nginx
sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
printf "http {\nserver {\nlisten 80;\nroot /var/www/data/;\n}\n}\nevents{}" | sudo tee -a /etc/nginx/nginx.conf
mkdir /var/www/data
printf "Hello World" | sudo tee -a /var/www/data/index.html
sudo nginx -s reload
